package a00953080.comp3717.bcit.ca.newwesttriviaapp.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "HIGH_SCORE".
 */
@Entity
public class HighScore {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String name;
    private int score;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public HighScore() {
    }

    public HighScore(Long id) {
        this.id = id;
    }

    @Generated
    public HighScore(Long id, String name, int score) {
        this.id = id;
        this.name = name;
        this.score = score;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
