package a00953080.comp3717.bcit.ca.newwesttriviaapp.questions.schema;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "QUESTION".
*/
public class QuestionDao extends AbstractDao<Question, Long> {

    public static final String TABLENAME = "QUESTION";

    /**
     * Properties of entity Question.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Question = new Property(1, String.class, "question", false, "QUESTION");
        public final static Property Answer = new Property(2, String.class, "answer", false, "ANSWER");
        public final static Property Option1 = new Property(3, String.class, "option1", false, "OPTION1");
        public final static Property Option2 = new Property(4, String.class, "option2", false, "OPTION2");
        public final static Property Option3 = new Property(5, String.class, "option3", false, "OPTION3");
    }


    public QuestionDao(DaoConfig config) {
        super(config);
    }
    
    public QuestionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"QUESTION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"QUESTION\" TEXT NOT NULL ," + // 1: question
                "\"ANSWER\" TEXT NOT NULL ," + // 2: answer
                "\"OPTION1\" TEXT NOT NULL ," + // 3: option1
                "\"OPTION2\" TEXT NOT NULL ," + // 4: option2
                "\"OPTION3\" TEXT NOT NULL );"); // 5: option3
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QUESTION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Question entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getQuestion());
        stmt.bindString(3, entity.getAnswer());
        stmt.bindString(4, entity.getOption1());
        stmt.bindString(5, entity.getOption2());
        stmt.bindString(6, entity.getOption3());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Question entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getQuestion());
        stmt.bindString(3, entity.getAnswer());
        stmt.bindString(4, entity.getOption1());
        stmt.bindString(5, entity.getOption2());
        stmt.bindString(6, entity.getOption3());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Question readEntity(Cursor cursor, int offset) {
        Question entity = new Question( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // question
            cursor.getString(offset + 2), // answer
            cursor.getString(offset + 3), // option1
            cursor.getString(offset + 4), // option2
            cursor.getString(offset + 5) // option3
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Question entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuestion(cursor.getString(offset + 1));
        entity.setAnswer(cursor.getString(offset + 2));
        entity.setOption1(cursor.getString(offset + 3));
        entity.setOption2(cursor.getString(offset + 4));
        entity.setOption3(cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Question entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Question entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Question entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
